#!/bin/sh
# Install playora-agent binary + menu entries DIRECTLY onto the mounted dArkOSRE SD.
# No SSH needed. After this, eject the SD, boot the R36S, and access Playora from
# the EmulationStation "Ports" menu.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$ROOT/dist/playora-agent-aarch64"
[ -f "$BIN" ] || { echo "Build first: sh scripts/build-container.sh"; exit 1; }

# The dArkOSRE SD mounts EASYROMS (and on first boot, a second 'roms' rootfs partition).
# We can drop the binary into /Volumes/EASYROMS/.playora/ and ports/ scripts that exec it
# via a path that exists after boot. dArkOSRE bind-mounts EASYROMS at /roms.
SD="${SD:-/Volumes/EASYROMS}"
[ -d "$SD" ] || { echo "$SD not mounted. Insert the dArkOSRE SD."; exit 1; }

PLAYORA_DIR="$SD/.playora"
PORTS_DIR="$SD/ports"
mkdir -p "$PLAYORA_DIR" "$PORTS_DIR"

echo "[install] copying agent binary to SD"
cp "$BIN" "$PLAYORA_DIR/playora-agent"
chmod 0755 "$PLAYORA_DIR/playora-agent"

# Each menu entry is a tiny .sh that EmulationStation lists in Ports.
write_port() {
    name="$1"; cmd="$2"
    file="$PORTS_DIR/Playora ${name}.sh"
    cat > "$file" <<EOF
#!/bin/sh
# Generated by playora install-to-sd.sh.
# dArkOSRE bind-mounts EASYROMS at /roms, so this path always resolves at runtime.
cd /roms/.playora
./playora-agent ${cmd}
EOF
    chmod 0755 "$file"
    echo "[install] wrote $file"
}

write_port "Hub"             "tui"
write_port "PortMaster"      "tui"
write_port "Update"          "self-update"
write_port "Saves Backup"    "saves upload"
write_port "Doctor"          "doctor"
write_port "Hardware"        "hardware snapshot"

# First-run agent config (only if missing)
CFG="$PLAYORA_DIR/agent.toml"
if [ ! -f "$CFG" ]; then
    SERVER_URL="${PLAYORA_SERVER_URL:-http://192.168.3.82:8080}"
    cat > "$CFG" <<EOF
device_id = "dev_$(uuidgen | tr -d '-' | tr 'A-Z' 'a-z' | cut -c1-32)"
device_name = "R36S"
device_profile = "r36s-darkosre-clone"
os_family = "darkosre-r36"
server_url = "$SERVER_URL"
rom_paths = ["/roms"]
save_paths = ["/roms/savestates"]
metadata_paths = ["/roms"]
scan_interval_minutes = 60
sync_interval_seconds = 60
max_batch_size = 100
enable_runtime_probe = false
enable_retroarch_network_control = false
retroarch_udp_port = 55355
enable_catalog = true
enable_hardware_tests = true
enable_resource_sampling = true
log_level = "info"
EOF
    echo "[install] wrote config: $CFG (server=$SERVER_URL)"
fi

# Tell the agent where to find its config when invoked from Ports.
for f in "$PORTS_DIR/Playora "*.sh; do
    sed -i '' 's|./playora-agent |./playora-agent --config /roms/.playora/agent.toml |' "$f"
done

echo
echo "============================================================"
echo "  Playora installed on SD."
echo "  Eject the SD, insert it in the R36S, boot, then go to:"
echo "      EmulationStation → Ports → Playora Hub"
echo "  Server URL: $(grep server_url "$CFG" | head -1)"
echo "  Change later: edit $CFG before boot."
echo "============================================================"
sync; sync
