#!/bin/sh
# Install Playora menu entries into dArkOSRE Ports/Tools so they appear in EmulationStation.
# Backs up any existing entries with the same name.
set -eu
PORTS_DIR="${PORTS_DIR:-/roms/ports}"
TOOLS_DIR="${TOOLS_DIR:-/roms/tools}"
[ -d "$PORTS_DIR" ] || { echo "[playora] no $PORTS_DIR; skipping ports menu"; exit 0; }

backup_if_exists() {
    f="$1"
    [ -f "$f" ] && cp -p "$f" "$f.bak.$(date +%Y%m%d_%H%M%S)"
}

write_port() {
    name="$1"; cmd="$2"
    file="$PORTS_DIR/Playora ${name}.sh"
    backup_if_exists "$file"
    cat > "$file" <<EOF
#!/bin/sh
# Generated by install-darkosre-menu.sh
exec /usr/local/bin/playora-agent ${cmd}
EOF
    chmod +x "$file"
    echo "[playora] wrote $file"
}

write_port "Status"        "tui --screen status"
write_port "Sync Now"      "sync"
write_port "Doctor"        "doctor --interactive"
write_port "Hardware Test" "hardware test --interactive"
write_port "Catalog"       "catalog list --interactive"
write_port "Features"      "features show"
write_port "Logs"          "logs tail"

echo "[playora] done. ES will pick these up after restart."
