#!/bin/sh
# install-to-sd: drop binary + agent.toml + Ports menu .sh files onto the mounted
# dArkOSRE SD. Each .sh uses the proper "stop ES, run with TTY, restart ES"
# pattern so output is visible on the framebuffer.
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$ROOT/dist/playora-agent-aarch64"
[ -f "$BIN" ] || { echo "Build first: sh scripts/build-container.sh"; exit 1; }

SD="${SD:-/Volumes/EASYROMS}"
[ -d "$SD" ] || { echo "$SD not mounted. Insert the dArkOSRE SD."; exit 1; }

PLAYORA_DIR="$SD/.playora"
PORTS_DIR="$SD/ports"
LOG_DIR="$SD/.playora/logs"
mkdir -p "$PLAYORA_DIR" "$PORTS_DIR" "$LOG_DIR"

echo "[install] copying agent binary"
cp "$BIN" "$PLAYORA_DIR/playora-agent"
chmod 0755 "$PLAYORA_DIR/playora-agent"

# Each .sh runs the agent with proper TTY + ES restart pattern.
# Args:
#  $1 = port display name (used for .sh filename)
#  $2 = mode: "tui" (interactive, stop ES), "task" (run, show output, pause)
#  $3 = command + args passed to playora-agent
write_port() {
    name="$1"; mode="$2"; cmd="$3"
    file="$PORTS_DIR/Playora ${name}.sh"
    safe_name="$(echo "$name" | tr ' ' '_')"

    if [ "$mode" = "tui" ]; then
        cat > "$file" <<EOF
#!/bin/bash
# Generated by playora install-to-sd.sh — TUI mode (stops ES, real TTY)
LOG="/roms/.playora/logs/${safe_name}_\$(date +%Y%m%d_%H%M%S).log"
exec > "\$LOG" 2>&1

# kill ES (multiple methods for resilience)
sudo systemctl stop emulationstation 2>/dev/null
sudo killall -9 emulationstation 2>/dev/null
sudo killall -9 retroarch 2>/dev/null
sleep 1

# Run on the framebuffer console (tty1 is typical on R36S)
TTY=/dev/tty1
[ -w "\$TTY" ] || TTY=/dev/console
{
    clear
    cd /roms/.playora
    ./playora-agent --config /roms/.playora/agent.toml ${cmd}
    echo
    echo "==== Pressione START pra voltar pra EmulationStation ===="
    read -n 1 -s
} <"\$TTY" >"\$TTY" 2>&1

# restart ES
sudo systemctl start emulationstation 2>/dev/null \\
    || sudo systemctl restart emulationstation 2>/dev/null \\
    || (cd /; nohup sudo -u ark emulationstation >/dev/null 2>&1 &) \\
    || (cd /; nohup emulationstation >/dev/null 2>&1 &)
EOF
    else
        # "task" mode: don't stop ES, run, dump output to log, show with whiptail/dialog/cat
        cat > "$file" <<EOF
#!/bin/bash
# Generated by playora install-to-sd.sh — task mode (runs in background of ES)
LOG="/roms/.playora/logs/${safe_name}_\$(date +%Y%m%d_%H%M%S).log"
{
    echo "==== \$(date) ===="
    cd /roms/.playora
    ./playora-agent --config /roms/.playora/agent.toml ${cmd}
    echo
    echo "Exit code: \$?"
} > "\$LOG" 2>&1

# Best-effort show:
if command -v whiptail >/dev/null 2>&1; then
    sudo killall -STOP emulationstation 2>/dev/null
    TTY=/dev/tty1
    [ -w "\$TTY" ] || TTY=/dev/console
    whiptail --title "Playora — ${name}" --textbox "\$LOG" 22 78 <"\$TTY" >"\$TTY" 2>&1
    sudo killall -CONT emulationstation 2>/dev/null
elif command -v dialog >/dev/null 2>&1; then
    sudo killall -STOP emulationstation 2>/dev/null
    TTY=/dev/tty1
    [ -w "\$TTY" ] || TTY=/dev/console
    dialog --title "Playora — ${name}" --textbox "\$LOG" 22 78 <"\$TTY" >"\$TTY" 2>&1
    sudo killall -CONT emulationstation 2>/dev/null
fi

# Always sync to server so user can see it in dashboard:
cd /roms/.playora && ./playora-agent --config ./agent.toml sync >/dev/null 2>&1 || true
EOF
    fi
    chmod 0755 "$file"
    echo "[install] wrote ${file}"
}

# Menu entries
write_port "Hub"             "tui"  "tui"
write_port "PortMaster"      "tui"  "tui"
write_port "Restore Backup"  "tui"  "restore-tar"
write_port "Doctor"          "task" "doctor"
write_port "Hardware"        "task" "hardware snapshot --save"
write_port "Update"          "tui"  "self-update"
write_port "Saves Backup"    "task" "saves upload"

# First-run config (only if missing)
CFG="$PLAYORA_DIR/agent.toml"
if [ ! -f "$CFG" ]; then
    SERVER_URL="${PLAYORA_SERVER_URL:-http://192.168.3.82:8080}"
    DEVICE_ID="dev_$(uuidgen | tr -d '-' | tr 'A-Z' 'a-z' | cut -c1-32)"
    cat > "$CFG" <<EOF
device_id = "$DEVICE_ID"
device_name = "R36S"
device_profile = "r36s-darkosre-clone"
os_family = "darkosre-r36"
server_url = "$SERVER_URL"
rom_paths = ["/roms"]
save_paths = ["/roms/savestates"]
metadata_paths = ["/roms"]
scan_interval_minutes = 60
sync_interval_seconds = 60
max_batch_size = 100
enable_runtime_probe = false
enable_retroarch_network_control = false
retroarch_udp_port = 55355
enable_catalog = true
enable_hardware_tests = true
enable_resource_sampling = true
log_level = "info"
EOF
    echo "[install] wrote config: $CFG (server=$SERVER_URL)"
fi

# Remove broken legacy vendor scripts (clone firmware leftovers)
LEGACY_SCRIPTS="
$SD/tools/R36S-Backup.sh
$SD/tools/R36S-Search.sh
$SD/tools/R36S-Install-Collections.sh
$SD/tools/R36S-Smart.sh
$SD/tools/R36S-Storage.sh
"
for s in $LEGACY_SCRIPTS; do
    if [ -f "$s" ]; then
        mv "$s" "$s.disabled" 2>/dev/null || true
        echo "[install] disabled legacy script: $s"
    fi
done

sync
echo
echo "============================================================"
echo "  Playora installed."
echo "  Eject SD, boot R36S, ES → Ports → Playora Hub"
echo "  Logs at: /roms/.playora/logs/"
echo "============================================================"
